### ISSUE TITLE
Build Script Assets Structure Mismatch

### ISSUE THREAD

**Issue by duytnguyendtn** [JTPond/calcifyarchive#2]
This might end up being a [DUE](https://en.wikipedia.org/wiki/User_error), but figured I'd report it anyways in case it's an actual bug. In worst case it can serve as a useful breadcrumb for a new user down the line!

# Issue Description
While working on #1, I realized some of the SVG assets weren't loading on build:
![image](https://user-images.githubusercontent.com/25206008/123894046-800ba500-d92b-11eb-9475-5927e6fd07a1.png)
I looked into `main.ts` and think I found a potential structure mismatch?

In the typescript code, it looks like all the asset sources are pointing to an `asset` folder inside of the `style` folder:
https://github.com/JTPond/calcifyarchive/blob/1c96f096e82292f0a894dc51571f0c4fb81d1506/static/ts/main.ts#L70
and indeed `browser.svg` is located in the `asset` subdirectory on this repo's static
https://github.com/JTPond/calcifyarchive/blob/1c96f096e82292f0a894dc51571f0c4fb81d1506/static/style/assets/browser.svg

Yet it seems the build scripts are all copying the assets into the `dist`'s style folder, no `asset` subfolder:
![image](https://user-images.githubusercontent.com/25206008/123895181-6a977a80-d92d-11eb-91c4-585feb03a074.png)
https://github.com/JTPond/calcifyarchive/blob/1c96f096e82292f0a894dc51571f0c4fb81d1506/static/build.bat#L6
https://github.com/JTPond/calcifyarchive/blob/1c96f096e82292f0a894dc51571f0c4fb81d1506/static/build.sh#L6

such that when I run a simple HTTP server, I get the following error:
```
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
::ffff:127.0.0.1 - - [29/Jun/2021 22:41:15] "GET / HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [29/Jun/2021 22:41:15] "GET /style/css/stylesheet.css HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [29/Jun/2021 22:41:15] "GET /js/main.js HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [29/Jun/2021 22:41:15] "GET /js/components/pathWizard.js HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [29/Jun/2021 22:41:15] "GET /js/components/folderComp.js HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [29/Jun/2021 22:41:15] "GET /js/components/articleComp.js HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [29/Jun/2021 22:41:15] "GET /js/components/tbarControls.js HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [29/Jun/2021 22:41:15] "GET /js/components/hplink.js HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [29/Jun/2021 22:41:15] "GET /index.json HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [29/Jun/2021 22:41:15] "GET /style/assets/browser.svg HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [29/Jun/2021 22:41:15] code 404, message File not found
::ffff:127.0.0.1 - - [29/Jun/2021 22:41:15] "GET /favicon.ico HTTP/1.1" 404 -
```
of particular note:
```
::ffff:127.0.0.1 - - [29/Jun/2021 22:41:15] "GET /style/assets/browser.svg HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [29/Jun/2021 22:41:15] code 404, message File not found
```
# Mitigation
When I manually create an `asset` folder in the built style folder, the image renders properly:
![image](https://user-images.githubusercontent.com/25206008/123895092-420f8080-d92d-11eb-99b8-c7e0ecbaa57e.png)
![image](https://user-images.githubusercontent.com/25206008/123895124-4f2c6f80-d92d-11eb-8088-0a67b7108db2.png)

# Potential Solution
Based on my understanding, I think there are two technical solutions here, one of which are probably what you're envisioning @JTPond . I'm a backend person so I don't know which is the *right* solution 😆 

## Solution 1: Update the build scripts to copy the assets folder over in its entirety:
For `build.bat`:
`copy /y .\style\assets\* ..\dist\style\assets. `
and for `build.sh`:
`cp -R ./style/assets ../dist/style/assets.;`
and #1 should be updated to:
`Copy-Item .\style\assets\* ..\dist\style\assets`

## Solution 2: Keep the built assets in the root style folder, modify `main.ts` to instead say:
`browser_btn.src = "./style/browser.svg";`

**Comment by JTPond** [comment]
So, the shell script is actually correct for *nix systems. At least when I run it in two different versions of Debian. That `cp -r` copies the assets folder and all of its subfolders as expected. This is just more of my lack of experience with cmd/batch/powershell. Do you think this can be rolled into the PR, and just update the powershell to work the same way?

**Comment by duytnguyendtn** [comment]
Sure thing! On it...
